// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadDotenv } from "dotenv";
import { defineConfig } from "prisma/config";

loadDotenv({ path: ".env.local", override: true });
loadDotenv({ path: ".env", override: false });

const databaseUrl = process.env["DATABASE_URL"];
const directUrl = process.env["DIRECT_URL"];

const migrationUrl = directUrl ?? databaseUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationUrl,
  },
});
