// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env["DATABASE_URL"];
const directUrl = process.env["DIRECT_URL"];

const migrationUrl = (() => {
  if (directUrl) return directUrl;
  if (!databaseUrl) return undefined;

  const parsedUrl = new URL(databaseUrl);
  parsedUrl.searchParams.set("pgbouncer", "true");
  parsedUrl.searchParams.set("connection_limit", "1");
  return parsedUrl.toString();
})();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationUrl,
  },
});
